# Sample configuration file for the 
sample:
  name: "Test"  # Name of the sample ex: "MRG6N1"
  device: "test"  # location of the device ex: "x1y6"

# Load Instrument
instrument:
  model: "sim"  # name of the sourcemeter file without .py ex: "keithley_2400"
  address: "GPIB0::24::INSTR"  # address of the sourcemeter ex: "GPIB0::24::INSTR"


pulsedIV:
  cycle: "+-"  # cycle of the voltage (ex: "+-","-+", "+" or "-")
  n_cycles: 2  # number of cycles
  v+:  2.0 # maximum voltage value of positive cycle
  v-: -2.0  # minimum voltage value of negative cycle
  v_step: 0.5  # voltage step
  v_read: 0.05  # voltage step for the read
  ccplc: 0.1  # current compliance
  t_write: 0.00001  # time between each voltage step
  t_read: 0.00001  # time between each current read
  t_wait: 0.00001  # time between each cycle
  nplc: 2  # number of power line cycles


